/**
Programmer:			Sean Thames
Date:				2013-06-20
Filename:			GadgetOrderTaker.java
Assignment:			Ch 12 Ex 12
Description:		a) Gadgets by Mail sells man interesting items through
its catalogs. Write an application that prompts the user for order detauls,
including item numbers and quantity of each item ordered, based on the 
available items shown in Table 12-2.

Table 12-2
-----------------------------------------------------------
Item #		Description							Price($)
-----------------------------------------------------------
101			Electric hand warmer				12.99
124			Battery-operated plant waterer		7.55
256			Gerbil trimmer						9.99
512			Talking bookmark					6.89
-----------------------------------------------------------

The shipping and handling fee for an order is based on the total price, as
shown in Table 12.3.

Table 12-3
-----------------------------------------------------------
Price of Order($)				Shipping and Handling($)
-----------------------------------------------------------
0-24.99							5.55
25.00-49.99						8.55
50.00 or more					11.55
-----------------------------------------------------------

Create the following classes:
 >	Gadget, which contains an item number, description, and price for a 
	gadget; a constructor that sets all the fields; and get methods to 
	retrieve the field values.
 >	Order, which contains an order number, customer name, and address 
	(assume you need just a street address, not city, state, and zip code);
	a list of item numbers ordered (up to four); the total price of all items
	ordered; and a shipping and handling fee for the order. Include a 
	constructor to set the field values and get methods to retrieve the 
	field values.
 >	GadgetOrderTaker, which is an interactive application that takes four 
	customer orders. The class contains an array of the four Gadget objects 
	offered (from Table 12-2). The application prompts each user for a name and
	street address and assigns a unique order number to each customer, starting
	with 101. The application asks each user to enter an item number and 
	quantity wanted. When the user enters 999 for the item number the order is 
	complete, and the next customer can enter data. Each customer can order up
	to four item numbers. When a customer's order is complete (the customer has
	entered 999 for an item number, or has ordered four different items), 
	calculate the shipping and handling charges. After four customers have 
	placed Orders, display each Order's data, including the order number, the 
	name and address of the customer, and the list of tiems ordered, including 
	the item number, description, and price of each Order, the total price for 
	the order, and the shipping and handling charge. The GadgetOrderTaker class
	handles all thrown Exceptions by displaying an explanatory message and 
	ending the application.
>	OrderException, which is an Exception that is created and thrown under any 
	of the following conditions:
	- A customer attempts to order more than four different items. 
	- A customer orders more than 100 of any item.
	- A customer enters an invalid item number
>	Also, catch the Exception generated by either of these conditions:
	- A customer enters a nonnumeric character as the item number.
	- A customer enters a nonnumeric character as the quantity.

Save the files as Gadget.java, Order.java, GadgetOrderTaker.java, and 
OrderException.java.

b) The GadgetOrderTaker class handles all thrown Exceptions by displaying an
explanatory message and ending the application. Create a new application that 
handles all Exceptions by requiring the user to reenter the offending data. 
Save the file as GadgetOrderTaker2.java
*/

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.text.NumberFormat;

public class GadgetOrderTaker2
{
	private static Gadget[] gadgetList; // so I don't need to pass it
	
	public static void main(String[] args)
	{
		final int ORDER_NUMBER_SEED = 101;
		
		gadgetList = getGadgetList();
		Order[] orderList = new Order[4];
		
		try 
		{
			for(int i = 0; i < orderList.length; i++)
			{
				orderList[i] = getOrder(ORDER_NUMBER_SEED + i);
				if(orderList[i].getTotalPrice() == 0.0)
					throw(new OrderException("Order #" + orderList[i].getOrderNumber() + " is blank."));
			}
			for(Order o: orderList)
				displayOrder(o);
		}
		catch(Exception e)
		{
			JOptionPane.showMessageDialog(null, e.getMessage());
			System.exit(1);
		}
	}
	
	public static Order getOrder(int number) throws OrderException
	{
		final int LIMIT = 100;
		final double[] SHIPPING_SCALE = {24.00, 49.99};
		final double[] SHIPPING_COST = {5.55, 8.55, 11.55};
		
		String customerName;
		String customerAddress;
		ArrayList<String> itemList = new ArrayList<String>();
		int[] items;
		int tempItem = 0;
		double totalPrice = 0.0;
		double shippingHandling;
		Order order;
		String userInput;
		boolean again = true;
		int i = 0;
		int quantity;
		
		customerName = input("Please enter the customer name: ");
		customerAddress = input("Please enter the customer address: ");
		
		
		do
		{
			userInput = input("Enter item number: ");
			try
			{
				tempItem = Integer.parseInt(userInput); // make sure it is a number
				
				if(tempItem != 999)
				{
					itemList.add(userInput);
					if(getDescription(tempItem).equals(""))
						throw(new OrderException("Invalid item number"));
					userInput = input("Quantity of item #" + tempItem + ": ");
					quantity = Integer.parseInt(userInput);
					if(quantity > LIMIT)
						throw(new OrderException(quantity + " exceeds the item quantity limit!"));
					else
						totalPrice += getCost(tempItem, quantity);
				}
				else
					again = false;
			}
			catch(OrderException e)
			{
				JOptionPane.showMessageDialog(null, e.getMessage());
				continue;
			}
			catch(NumberFormatException e)
			{
				JOptionPane.showMessageDialog(null, userInput + " is not a valid number.");
				continue;
			}
		} while(again);
		
		if(itemList.size() > gadgetList.length)
			throw(new OrderException("Items ordered exceeds available items!"));
		else
			items = new int[itemList.size()];
		
		for(i = 0; i < items.length; i++)
		{
			items[i] = Integer.parseInt(itemList.get(i));
		}
		
		if(totalPrice < SHIPPING_SCALE[0])
			shippingHandling = SHIPPING_COST[0];
		else if (totalPrice > SHIPPING_SCALE[0] && totalPrice < SHIPPING_SCALE[1])
			shippingHandling = SHIPPING_COST[1];
		else
			shippingHandling = SHIPPING_COST[2];
		
		order = new Order(number, customerName, customerAddress, items, totalPrice, shippingHandling);
		
		
		return order;
	}
	public static String input(String s)
	{
		// This is easier than typing it dozens of times
		return JOptionPane.showInputDialog(null, s);
	}
	public static double getCost(int num, int q) throws OrderException
	{
		for(Gadget g : gadgetList)
			if(g.getItemNumber() == num)
				return (g.getPrice() * q);
				
		throw(new OrderException("Item #" + num + " is not a valid item"));
	}
	
	public static void displayOrder(Order o)
	{
		int[] orderedItems = o.getItemList();
		
		NumberFormat money = NumberFormat.getCurrencyInstance();
		
		String price = money.format(o.getTotalPrice());
		String shipping = money.format(o.getShippingHandling());
		String total = money.format(o.getTotalPrice() + o.getShippingHandling());
		
		String message = new String();
		message = "Order #" + o.getOrderNumber() + "\n";
		message += "Customer: " + o.getCustomerName() + "\n";
		message += "Address: " + o.getCustomerAddress() + "\n";
		message += "-------------------------------------\n";
		
		for(int item : orderedItems)
		{
			message += item + "        ";
			message += getDescription(item) + "\n";
			
		}
		
		message += "-------------------------------------\n";
		message += "Price:    " + price + "\n";
		message += "S/H:       " + shipping + "\n";
		message += "Total:    " + total;
		
		JOptionPane.showMessageDialog(null, message);
	}
	public static String getDescription(int num)
	{
		for(Gadget g : gadgetList)
		{
			if(g.getItemNumber() == num)
				return g.getDescription();
		}
		
		return "";
	}
	
	public static Gadget[] getGadgetList()
	{
		/* 
		 * Did this because normally the item list would not be hard coded and 
		 * you would call a function to load the list into memory.
		 */
		 Gadget[] gadgets = new Gadget[4];
		 gadgets[0] = new Gadget(101, "Electric Hand warmer", 12.99);
		 gadgets[1] = new Gadget(124, "Battery-operated plant waterer", 7.55);
		 gadgets[2] = new Gadget(256, "Gerbil trimmer", 9.99);
		 gadgets[3] = new Gadget(512, "Talking bookmark", 6.89);
		 
		 return gadgets;
	 }
}
